[tool.pylint.messages_control]
disable = [
    "C0114",  # missing-module-docstring
    "C0115",  # missing-class-docstring
    "C0116"   # missing-function-docstring
]

[tool.pylint.format]
max-line-length = 88

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311", "py312"]
