[tool.pylint."MESSAGES CONTROL"]
disable = ["C0114", "C0115", "C0116"]  # Must be a list of strings

[tool.pylint.format]
max-line-length = 88

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311", "py312"]
